// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFjY7HyRUariC7uPbIwjuTpXkAGoG8Tck',
    appId: '1:579827544322:web:0ee2ab9bf13c2ddc86d21b',
    messagingSenderId: '579827544322',
    projectId: 'courseworktwo-58b38',
    authDomain: 'courseworktwo-58b38.firebaseapp.com',
    storageBucket: 'courseworktwo-58b38.appspot.com',
    measurementId: 'G-DK6DXQEQCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJaouXwDUGAHJYzvBoqN9w4ktmmNxsEw',
    appId: '1:579827544322:android:6989b65cd6525c5086d21b',
    messagingSenderId: '579827544322',
    projectId: 'courseworktwo-58b38',
    storageBucket: 'courseworktwo-58b38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRxbmxhhHWBWfJmtCwlTmG7pIWtCSSgM',
    appId: '1:579827544322:ios:2215515715f7724d86d21b',
    messagingSenderId: '579827544322',
    projectId: 'courseworktwo-58b38',
    storageBucket: 'courseworktwo-58b38.appspot.com',
    iosClientId: '579827544322-tgm3dbhjqsgu7egltt0v4fnn0kd3940u.apps.googleusercontent.com',
    iosBundleId: 'com.c',
  );
}
